name: desktop_widget
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  desktop_multi_window: ^0.2.0
  window_manager: ^0.4.2
  intl: ^0.19.0
  calendar_view:
    path: ./local_packages/flutter_calendar_view-master/

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

